### ISSUE TITLE
[BUG] Use x-forwarded-for header

### ISSUE THREAD

**Issue by AntonioRodriguezRuiz** [FIS2425/staff-svc#14]
## Description

When accessing the ip of the request in a microservice, we expect the ip of the user, not the API Gateway

## Steps to Reproduce

1. Activate a microservice and the api-gateway
2. Send a request via the api gateway to the microservice
3. Note the ip address logged in the microservice is the ip of the api-gateway

## Expected Behavior

The IP of the user is forwarded

## Actual Behavior

The IP of the user is not forwarded

## Proposed fix

Change instances of `req.ip` to `req.headers && req.headers['x-forwarded-for'] || req.ip`

**Comment by AitorRD** [comment]
This issue was resolved in #23
